spring:
  config:
    activate:
      on-profile: local # 어플리케이션의 프로파일 설정

  jpa:
    hibernate:
      ddl-auto: update  # 테이블이 없을 경우 생성, 테이블이 있을 경우 변경사항을 반영
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 100
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/conolja-local?currentSchema=conolja
    username: mwjeong
    password: Wsxqaz1425!

springdoc:
  servers:
    - "http://localhost:8080${server.servlet.context-path}"
